In [42]:
import torch
from torch import nn
import numpy as np

In [15]:
net = nn.Conv1d(3,64,1)
x = torch.randn(1,3,99)
net(x).shape

torch.Size([1, 64, 99])

In [29]:
x = torch.randn(1,1024,99)

In [30]:
y = torch.max(x, 2, keepdim=True)[0] # returns values and indices
y.shape

torch.Size([1, 1024, 1])

In [34]:
z = y.view(-1, 1024)
z.shape

torch.Size([1, 1024])

In [39]:
z2 = y.squeeze(2)
z2.shape

torch.Size([1, 1024])

In [40]:
z

tensor([[3.3439, 2.2972, 2.3745,  ..., 3.0625, 2.1741, 2.6859]])

In [41]:
z2

tensor([[3.3439, 2.2972, 2.3745,  ..., 3.0625, 2.1741, 2.6859]])

In [44]:
torch.autograd.Variable(torch.from_numpy(np.array([1,0,0,0,1,0,0,0,1]).astype(np.float32))).view(1,9).repeat(16,1)

tensor([[1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1., 0., 0., 0., 1.]])

In [47]:
torch.from_numpy(np.array([1,0,0,0,1,0,0,0,1]).astype(np.float32)).shape


torch.Size([9])

In [48]:
torch.from_numpy(np.array([1,0,0,0,1,0,0,0,1]).astype(np.float32)).view(1,9).shape


torch.Size([1, 9])