In [1]:
import torch
import numpy as np

# https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [2]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [4]:
# indexing and slicing
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")


tensor([[0.2254, 0.4938, 0.4818, 0.7312],
        [0.3369, 0.5657, 0.1022, 0.8031],
        [0.8363, 0.8942, 0.2580, 0.3718]])
First row: tensor([0.2254, 0.4938, 0.4818, 0.7312])
First column: tensor([0.2254, 0.3369, 0.8363])
Last column: tensor([0.7312, 0.8031, 0.3718])


In [11]:
t1 = torch.cat([tensor,tensor],dim = 1)
t0 = torch.cat([tensor,tensor],dim = 0)
print(t0)
print(t1)

tensor([[0.2254, 0.4938, 0.4818, 0.7312],
        [0.3369, 0.5657, 0.1022, 0.8031],
        [0.8363, 0.8942, 0.2580, 0.3718],
        [0.2254, 0.4938, 0.4818, 0.7312],
        [0.3369, 0.5657, 0.1022, 0.8031],
        [0.8363, 0.8942, 0.2580, 0.3718]])
tensor([[0.2254, 0.4938, 0.4818, 0.7312, 0.2254, 0.4938, 0.4818, 0.7312],
        [0.3369, 0.5657, 0.1022, 0.8031, 0.3369, 0.5657, 0.1022, 0.8031],
        [0.8363, 0.8942, 0.2580, 0.3718, 0.8363, 0.8942, 0.2580, 0.3718]])


## arithmetic operations

In [30]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
a = [1,2,3,4]
tensor = torch.tensor(a,dtype=float)
tensor = tensor.view(2,2)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print("y1 ",y1)
print("y2 ",y2)
print("y3 ",y3)

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print("z1 ",z1)
print("z2 ",z2)
print("z3 ",z3)

y1  tensor([[ 5., 11.],
        [11., 25.]], dtype=torch.float64)
y2  tensor([[ 5., 11.],
        [11., 25.]], dtype=torch.float64)
y3  tensor([[ 5., 11.],
        [11., 25.]], dtype=torch.float64)
z1  tensor([[ 1.,  4.],
        [ 9., 16.]], dtype=torch.float64)
z2  tensor([[ 1.,  4.],
        [ 9., 16.]], dtype=torch.float64)
z3  tensor([[ 1.,  4.],
        [ 9., 16.]], dtype=torch.float64)


## Resizing

In [33]:

T = torch.Tensor([1, 2, 3, 4, 5, 6])
print(T)

# Resize T to 2x3
x = T.view(2,3)
print("Tensor after resize:\n",x)

# Other way to resize T to 2x3
x = T.view(-1,3)
print("Tensor after resize:\n",x)

# Other way resize T to 2x3
x = T.view(2,-1)
print("Tensor after resize:\n",x)

tensor([1., 2., 3., 4., 5., 6.])
Tensor after resize:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
Tensor after resize:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
Tensor after resize:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])


# To numpy


In [34]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [35]:
# synchronize

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [36]:
n2 = np.ones(5)
t2 = torch.from_numpy(n2)


In [37]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]
